# Generated by Django 2.2.16 on 2021-09-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210913_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmation',
            old_name='user',
            new_name='user_id',
        ),
    ]
