# Generated by Django 2.2.16 on 2021-09-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210914_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='username',
            field=models.CharField(default='bobob', max_length=120),
            preserve_default=False,
        ),
    ]
