version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  yatube:
    image: fibboo/yatube:latest
    restart: always
    volumes:
      - static_value_yatube:/app/static/yatube/
      - media_value_yatube:/app/media/yatube/
    depends_on:
      - db
    env_file:
      - ./.env
  yamdb:
    image: fibboo/api_yamdb:latest
    restart: always
    volumes:
      - static_value_yamdb:/app/static/yamdb/
      - media_value_yamdb:/app/media/yamdb/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/html/certbot
      - static_value_yatube:/app/static/yatube/
      - media_value_yatube:/app/media/yatube/
      - static_value_yamdb:/app/static/yamdb/
      - media_value_yamdb:/app/media/yamdb/
    depends_on:
      - yatube
      - yamdb

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/html/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  static_value_yatube:
  media_value_yatube:
  static_value_yamdb:
  media_value_yamdb:
